---
to: apps/api/schemas/<%= name %>.py
---
"""
Schema for <%= name %> API endpoints.
Auto-generated by Hygen - customize as needed.
"""
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class <%= className %>Request(BaseModel):
    """Request schema for <%= name %> endpoint."""

    # TODO: Add request fields
    pass


class <%= className %>Response(BaseModel):
    """Response schema for <%= name %> endpoint."""

    # TODO: Add response fields
    success: bool = Field(default=True)
    message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class <%= className %>ListResponse(BaseModel):
    """List response schema for <%= name %> endpoint."""

    items: list[<%= className %>Response] = Field(default_factory=list)
    total: int = 0
    page: int = 1
    per_page: int = 20
